name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install Dependancies
      run: sudo apt-get install -y libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.0.0
      with:
        shared_key: sc_helper
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
